name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod 
      aws-assume-role-arn: "arn:aws:iam::302263044104:role/github-actions-joaoneves11-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "joaoneves-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "joaoneves11-sa-east-1-terraform-lock"



